name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test || echo "No tests"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/site_safety_monitor_oops || git clone https://github.com/JaswanthDara/site_safety_monitor_oops.git ~/site_safety_monitor_oops
          cd ~/site_safety_monitor_oops
          git pull origin main
          npm install
          sudo systemctl restart myapp   # must match your systemd service name
